##############################################################################
#                            Universe Collections                            #
#                 Created by Yozora, Bullmoose20, & Sohjiro                  #
#          EDITING THIS FILE MAY CAUSE PULLING NEW UPDATES TO FAIL           #
#      https://metamanager.wiki/en/latest/defaults/movie/universe.html       #
##############################################################################

external_templates:
  pmm: templates
  template_variables:
    collection_section: "040"

translations:
  pmm: translations

templates:
  universe:
    default:
      trakt_list_<<key>>: <<trakt_list>>
      name_mapping_<<key>>: <<name_mapping>>
      minimum_items: 2
    optional:
      - name_mapping
      - name_<<key>>
      - summary_<<key>>
      - imdb_list_<<key>>
    minimum_items: <<minimum_items>>
    name_mapping: <<name_mapping_<<key>>>>
    imdb_list: <<imdb_list_<<key>>>>
    trakt_list: <<trakt_list_<<key>>>>
    summary: <<summary_<<key>>>>
    name: <<name_<<key>>>>
    collection_mode: hide_items

collections:
  Universe Collections:
    template:
      - name: separator
        separator: universe
      - name: translation
        key_name: Universe
        translation_key: separator

dynamic_collections:
  Universe Collections:
    type: custom
    data:
      dca: DC Animated Universe
    template:
      - universe
      - shared
      - arr
      - custom
    template_variables:
      trakt_list:
        dca: https://trakt.tv/users/donxy/lists/dc-animated-movie-universe
      image:
        default: universe/<<key>>
  100 Horror Movies:
    type: custom
    data:
      100h: 100 Horror Movies
    collection_mode: default
    template:
      - universe
      - shared
      - arr
      - custom
   template_variables:
      trakt_list:
        100h: https://trakt.tv/users/andcbii/lists/100-horror-movies
