metadata:
  A Parks and Recreation Special:
    content_rating: TV-14
  Almost Heaven:
    content_rating: PG-13
  'Animaniacs: Wakko''s Wish':
    content_rating: TV-Y7
  Arsenic and Old Lace:
    content_rating: Approved
  Bad Boys:
    sort_title: Bad Boys_1995
  Bad Boys II:
    sort_title: Bad Boys_2003
  Bad Boys for Life:
    sort_title: Bad Boys_2020
  'Bad Boys: Ride or Die':
    sort_title: Bad Boys_2024
  'Batman & Mr. Freeze: SubZero':
    content_rating: TV-Y7
  Batman & Robin:
    sort_title: Batman_1997
  Batman Begins:
    sort_title: Batman_2005
  Batman Forever:
    sort_title: Batman_1995
  Batman Returns:
    sort_title: Batman_1992
  'Batman v Superman: Dawn of Justice':
    sort_title: Batman_2016
  'Batman: The Movie':
    sort_title: Batman_1966
    year: 1966
  Batman:
    sort_title: Batman_1989
    year: 1989
  'Battlestar Galactica: Razor':
    content_rating: TV-14
  'Battlestar Galactica: The Plan':
    content_rating: TV-14
  Bells Are Ringing:
    content_rating: Approved
  Bullitt:
    content_rating: PG
  Chase Me:
    content_rating: TV-Y7
  Clarissa:
    content_rating: TV-G
  CODA:
    content_rating: PG-13
  Cool Hand Luke:
    content_rating: PG
  Diamonds Are Forever:
    content_rating: PG
  Dinner Aboard the Bebop:
    content_rating: NR
  'Dragon Ball Z: Broly - Second Coming':
    match:
      mapping_id: 44251
    content_rating: PG-13
  'Dragon Ball Z: Cooler''s Revenge':
    content_rating: PG-13
  'Dragon Ball Z: Dead Zone':
    content_rating: PG-13
  'Dragon Ball Z: Lord Slug':
    content_rating: PG-13
  'Dragon Ball Z: Resurrection ''F''':
    content_rating: PG-13
  'Dragon Ball Z: The Return of Cooler':
    content_rating: PG-13
  'Dragon Ball Z: The Tree of Might':
    content_rating: PG-13
  'Dragon Ball Z: The World''s Strongest':
    content_rating: PG-13
  'Dragon Ball: The Path to Power':
    content_rating: PG-13
  'Dungeons & Dragons: Wrath of the Dragon God':
    content_rating: PG-13
  'Emma''s Wings: A Bella Sara Tale':
    content_rating: TV-G
  'Foo Fighters: Guardian Angels':
    content_rating: NR
  Funny Face:
    content_rating: Approved
  Gidget:
    content_rating: Approved
  Guys and Dolls:
    content_rating: Approved
  'Half-Shell Heroes: Blast to the Past':
    content_rating: TV-Y7
  Happy Holidays With Frank & Bing:
    match:
      mapping_id: 708829
    content_rating: G
  Heartless:
    content_rating: R
  High Society:
    content_rating: Approved
  How the Grinch Stole Christmas!:
    content_rating: TV-G
  In Search of Dr. Seuss:
    content_rating: TV-G
  It's Magic, Charlie Brown:
    content_rating: TV-G
  It's the Great Pumpkin, Charlie Brown:
    content_rating: TV-G
  Jeremiah Johnson:
    content_rating: PG
  Killer Joe:
    content_rating: NC-17
  Kites:
    content_rating: PG-13
  'LEGO Jurassic World: The Indominus Escape':
    content_rating: TV-G
  'Lego Batman: The Movie - DC Super Heroes Unite':
    content_rating: TV-G
  'Lego DC Comics Super Heroes: Justice League - Cosmic Clash':
    content_rating: TV-G
  'Lego DC Comics Superheroes: Justice League - Gotham City Breakout':
    content_rating: TV-G
  'Lego DC Super Heroes: Justice League - Attack of the Legion of Doom!':
    content_rating: TV-G
  Lost Transmissions:
    content_rating: R
  'Marvel Rising: Secret Warriors':
    content_rating: TV-Y7
  'Memo from Bebop: The Dub Sessions Remembered':
    content_rating: NR
  Miracle on 34th Street:
    content_rating: Approved
  'Mission: Impossible':
    sort_title: Mission_Impossible_1996
  'Mission: Impossible - Dead Reckoning':
    sort_title: Mission_Impossible_2023
  'Mission: Impossible - Fallout':
    sort_title: Mission_Impossible_2018
  'Mission: Impossible - Ghost Protocol':
    sort_title: Mission_Impossible_2011
  'Mission: Impossible - Rogue Nation':
    sort_title: Mission_Impossible_2015
  'Mission: Impossible II':
    sort_title: Mission_Impossible_2000
  'Mission: Impossible III':
    sort_title: Mission_Impossible_2006
  Mr. Deeds Goes to Town:
    content_rating: Approved
  Mr. Jones:
    content_rating: PG-13
  One Small Hitch:
    content_rating: PG-13
  Peter Pan1955:
    match:
      mapping_id: 368186
    content_rating: TV-G
    title: Peter Pan
    year: 1955
  Peter Pan1956:
    match:
      mapping_id: 721710
    content_rating: TV-G
    title: Peter Pan
    year: 1956
  Peter Pan1960:
    match:
      mapping_id: 51120
    content_rating: TV-G
    title: Peter Pan
    year: 1960
  Pirates of Silicon Valley:
    content_rating: TV-MA
  'Pokémon the Movie: Black - Victini and Reshiram':
    content_rating: TV-Y7
  'Pokémon the Movie: Diancie and the Cocoon of Destruction':
    content_rating: TV-Y7
  'Pokémon the Movie: Kyurem vs. the Sword of Justice':
    content_rating: TV-Y7
  'Pokémon the Movie: The Power of Us':
    content_rating: TV-Y7
  'Pokémon the Movie: White - Victini and Zekrom':
    content_rating: TV-Y7
  'Pokémon: Destiny Deoxys':
    content_rating: TV-Y7
  'Pokémon: Giratina and the Sky Warrior':
    content_rating: TV-Y7
  'Pokémon: Jirachi - Wish Maker':
    content_rating: TV-Y7
  'Pokémon: Lucario and the Mystery of Mew':
    content_rating: TV-Y7
  'Pokémon: Mewtwo Returns':
    content_rating: TV-Y7
  'Pokémon: The Rise of Darkrai':
    content_rating: TV-Y7
  'Pokémon: Zoroark - Master of Illusions':
    content_rating: TV-Y7
  Ride the Eagle:
    content_rating: R
  Servant Of The People 2:
    content_rating: TV-PG
  'Skin: A History of Nudity in the Movies':
    content_rating: R
  Taylor Hawkins Tribute Concert:
    match:
      mapping_id: 1013901
    content_rating: TV-PG
  The Animatrix:
    content_rating: R
  The Batman:
    sort_title: Batman_2022
  The Captain:
    content_rating: R
  The Harvey Girls:
    content_rating: Approved
  The Inbetweeners 2:
    content_rating: R
  'The Lion Guard: Return of the Roar':
    content_rating: TV-G
  The Philadelphia Story:
    content_rating: Approved
  The Rewrite:
    content_rating: PG-13
  The Seven Year Itch:
    content_rating: Approved
  The Shop Around the Corner:
    content_rating: Approved
  The Spine of Night:
    content_rating: NC-17
  The Twelve Chairs:
    content_rating: PG
  The Winning Season:
    match:
      mapping_id: 44750
    alt_title: Seeking for Justice Children
    originally_available: 2009-01-19T00:00:00.000Z
  Victory Through Air Power:
    content_rating: Approved
  Waiting for the Barbarians:
    content_rating: R
  We All Fall Down:
    content_rating: R
  White Christmas:
    content_rating: Approved
  Wuthering Heights:
    content_rating: Approved
  Zero Charisma:
    content_rating: PG-13
  Zoey's Extraordinary Christmas:
    content_rating: TV-14
    
  run_again: true