templates:
  auto-collection:
    tmdb_collection_details: <<value>>
    collection_order: release
    minimum_items: 2
    collection_mode: hide
  manual-collection:
    collection_mode: hide_items 
collections: 
  Pokémon Collection:
    template:
      name: manual-collection
    tmdb_collection_details:
      - 34055 #Pokémon Collection
      - 661029 #Pokémon: XY Collection
      - 661028 #Pokémon: Best Wishes! Collection
      - 661025 #Pokémon: Advanced Generation Collection
      - 661031 #Pokémon: Alternate Continuity Collection
      - 661026 #Pokémon: Diamond and Pearl Collection
    tmdb_movie:
      - 36897 #Pokémon: Mewtwo Returns (2001)
      - 571891 #Pokemon the Movie: Mewtwo Strikes Back - Evolution (2019)
dynamic_collections:
  TMDb Collections:          # This name is the mapping name
    template: auto-collection
    type: tmdb_collection
    remove_suffix: "Collection"
    exclude:
      - 34055 #Pokémon Collection
      - 661029 #Pokémon: XY Collection
      - 661028 #Pokémon: Best Wishes! Collection
      - 661025 #Pokémon: Advanced Generation Collection
      - 661031 #Pokémon: Alternate Continuity Collection
      - 661026 #Pokémon: Diamond and Pearl Collection
