templates:
  auto-collection:
    tmdb_collection_details: <<value>>
    collection_order: release
    minimum_items: 2
    collection_mode: hide
  manual-collection:
    collection_mode: hide_items 
collections: 
  Pokémon Collection:
    template:
      name: manual-collection
    tmdb_collection_details:
      - 34055 #Pokémon Collection
      - 661029 #Pokémon: XY Collection
      - 661028 #Pokémon: Best Wishes! Collection
      - 661025 #Pokémon: Advanced Generation Collection
      - 661031 #Pokémon: Alternate Continuity Collection
      - 661026 #Pokémon: Diamond and Pearl Collection
    tmdb_movie:
      - 36897 #Pokémon: Mewtwo Returns (2001)
      - 571891 #Pokemon the Movie: Mewtwo Strikes Back - Evolution (2019)
  Dragon Ball Collection:
    template:
      name: manual-collection
    sort_title: Dragon_Ball_1
    tmdb_collection_details:
      - 386410 #Dragon Ball Collection
  Dragon Ball Z Collection:
    template:
      name: manual-collection
    sort_title: Dragon_Ball_2
    tmdb_collection_details:
      - 425164 #Dragon Ball Z Collection
  Dragon Ball Super Collection:
    template:
      name: manual-collection
    sort_title: Dragon_Ball_3
    tmdb_collection_details:
      - 620873 #Dragon Ball Super Collection
  Dragon Ball Complete Collection:
    template:
      name: manual-collection
    url_poster: https://res.cloudinary.com/dkyd429md/image/upload/v1668802950/Plex%20-%20PMM%20images/dragonball_xljkad.jpg
    sort_title: Dragon_Ball_4
    tmdb_collection:
      - 386410 #Dragon Ball Collection
      - 425164 #Dragon Ball Z Collection
      - 620873 #Dragon Ball Super Collection
  Batman (DC Universe Animated) Collection:
    template:
      name: manual-collection
    sort_title: Batman_A_Animated
    tmdb_collection_details:
      - 421904 #Batman (DC Universe Animated) Collection
  Son of Batman Collection:
    template:
      name: manual-collection
    sort_title: Batman_B_Animated
    tmdb_collection_details:
      - 334996 #Son of Batman Collection
  Superman / Batman (Animated) Collection:
    template:
      name: manual-collection
    sort_title: Batman_C_Animated
    tmdb_collection_details:
      - 290933 #Superman / Batman (Animated) Collection
  Batman 80th Anniversary Collection:
    template:
      name: manual-collection
    url_poster: https://res.cloudinary.com/dkyd429md/image/upload/v1668795070/Plex%20-%20PMM%20images/Batman-80th-Anniversary-Collection_usl1u1.jpg
    sort_title: Batman_D_Animated
    tmdb_collection:
      - 421904 #Batman (DC Universe Animated) Collection
      - 334996 #Son of Batman Collection
      - 290933 #Superman / Batman (Animated) Collection
    tmdb_movie:
      - 485942 #Batman Ninja (2018)
      - 581997 #Batman vs. Teenage Mutant Ninja Turtles (2019)
      - 242643 #Batman: Assault on Arkham (2014)
      - 471474 #Batman: Gotham by Gaslight (2018)
      - 13851 #Batman: Gotham Knight (2008)
      - 411736 #Batman: Return of the Caped Crusaders (2016)
      - 472027 #Batman: The Dark Knight Returns (2013)
      - 382322 #Batman: The Killing Joke (2016)
      - 40662 #Batman: Under the Red Hood (2010)
      - 69735 #Batman: Year One (2011)
  LEGO DC Comics Super Heroes Collection:
    template:
      name: manual-collection
    tmdb_collection_details:
      - 386162 #LEGO DC Comics Super Heroes Collection
  Animaniacs:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 73901 #Animaniacs: Wakko's Wish (1999)
  Batman 1966:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 2661 #Batman (1966)
  Clarissa:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 395957 #Clarissa (1995)
  Cowboy Bebop:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 11299 #Cowboy Bebop: The Movie (2001)
  Deadwood:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 538225 #Deadwood: The Movie (2019)
  DuckTales:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 10837 #DuckTales: The Movie - Treasure of the Lost Lamp (1990)
  Friends:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 691179 #Friends: The Reunion (2021)
  G.I. Joe Collection:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 17421 #G.I. Joe: The Movie (1987)
  Lion Guard:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 359983 #The Lion Guard: Return of the Roar (2015)
  Parks and Recreation:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 696507 #A Parks and Recreation Special (2020)
  Power Rangers:
    template:
      name: manual-collection
    tmdb_collection_details:
      - 708816 #Power Rangers Collection
  The Simpsons:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 35 #The Simpsons Movie (2007)
  TMNT-2012:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 366861 #Half-Shell Heroes: Blast to the Past (2015)
  Transformers 1984:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 1857 #The Transformers: The Movie (1986)
  Zoey's Extraordinary:
    template:
      name: manual-collection
    tmdb_movie_details:
      - 872130 #Zoey's Extraordinary Christmas (2021)
  100 Horror Movies:
    trakt_list:
      - https://trakt.tv/users/andcbii/lists/100-horror-movies
    collection_order: custom
    sync_mode: sync
      
dynamic_collections:
  TMDb Collections:          # This name is the mapping name
    template: auto-collection
    type: tmdb_collection
    remove_suffix: "Collection"
    exclude:
      - 34055 #Pokémon Collection
      - 661029 #Pokémon: XY Collection
      - 661028 #Pokémon: Best Wishes! Collection
      - 661025 #Pokémon: Advanced Generation Collection
      - 661031 #Pokémon: Alternate Continuity Collection
      - 661026 #Pokémon: Diamond and Pearl Collection
      - 386410 #Dragon Ball Collection
      - 425164 #Dragon Ball Z Collection
      - 620873 #Dragon Ball Super Collection
      - 421904 #Batman (DC Universe Animated) Collection
      - 334996 #Son of Batman Collection
      - 386162 #LEGO DC Comics Super Heroes Collection
      - 290933 #Superman / Batman (Animated) Collection

