templates:
  auto-collection:
    tmdb_collection_details: <<value>>
    collection_order: release
    minimum_items: 2
    collection_mode: hide
  manual-collection:
    collection_mode: hide_items 
collections: 
  Pokémon Collection:
    template:
      name: manual-collection
    tmdb_collection_details:
      - 34055 #Pokémon Collection
      - 661029 #Pokémon: XY Collection
      - 661028 #Pokémon: Best Wishes! Collection
      - 661025 #Pokémon: Advanced Generation Collection
      - 661031 #Pokémon: Alternate Continuity Collection
      - 661026 #Pokémon: Diamond and Pearl Collection
    tmdb_movie:
      - 36897 #Pokémon: Mewtwo Returns (2001)
      - 571891 #Pokemon the Movie: Mewtwo Strikes Back - Evolution (2019)
  Dragon Ball Collection:
    template:
      name: manual-collection
    sort_title: Dragon_Ball_1
    tmdb_collection_details:
      - 386410 #Dragon Ball Collection
  Dragon Ball Z Collection:
    template:
      name: manual-collection
    sort_title: Dragon_Ball_2
    tmdb_collection_details:
      - 425164 #Dragon Ball Z Collection
  Dragon Ball Super Collection:
    template:
      name: manual-collection
    sort_title: Dragon_Ball_3
    tmdb_collection_details:
      - 620873 #Dragon Ball Super Collection
  Dragon Ball Complete Collection:
    template:
      name: manual-collection
    sort_title: Dragon_Ball_4
    tmdb_collection_details:
      - 386410 #Dragon Ball Collection
      - 425164 #Dragon Ball Z Collection
      - 620873 #Dragon Ball Super Collection
  Batman (DC Universe Animated) Collection:
    template:
      name: manual-collection
    sort_title: Batman_A_Animated
    tmdb_collection_details:
      - 421904 #Batman (DC Universe Animated) Collection
  Batman Animated Collection:
    template:
      name: manual-collection
    sort_title: Batman_B_Animated
    tmdb_movie:
      - 485942 #Batman Ninja (2018)
      - 581997 #Batman vs. Teenage Mutant Ninja Turtles (2019)
      - 321528 #Batman vs. Robin (2015)
      - 242643 #Batman: Assault on Arkham (2014)
      - 366924 #Batman: Bad Blood (2016)
      - 471474 #Batman: Gotham by Gaslight (2018)
      - 13851 #Batman: Gotham Knight (2008)
      - 537056 #Batman: Hush (2019)
      - 411736 #Batman: Return of the Caped Crusaders (2016)
      - 472027 #Batman: The Dark Knight Returns (2013)
      - 382322 #Batman: The Killing Joke (2016)
      - 40662 #Batman: Under the Red Hood (2010)
      - 69735 #Batman: Year One (2011)
dynamic_collections:
  TMDb Collections:          # This name is the mapping name
    template: auto-collection
    type: tmdb_collection
    remove_suffix: "Collection"
    exclude:
      - 34055 #Pokémon Collection
      - 661029 #Pokémon: XY Collection
      - 661028 #Pokémon: Best Wishes! Collection
      - 661025 #Pokémon: Advanced Generation Collection
      - 661031 #Pokémon: Alternate Continuity Collection
      - 661026 #Pokémon: Diamond and Pearl Collection
      - 386410 #Dragon Ball Collection
      - 425164 #Dragon Ball Z Collection
      - 620873 #Dragon Ball Super Collection
      - 421904 #Batman (DC Universe Animated) Collection

