templates:
  manual-shorts-collection:
    collection_mode: hide_items 
collections:
  Cars Toons:
    template:
      name: manual-shorts-collection
    tmdb_movie:
      - 56553
      - 140967
      - 39030
      - 24328
      - 171536
      - 148605
      - 148607
      - 148608
      - 148606
      - 145316
      - 141528
      - 230767
      - 296159
      - 296137
      - 286189
    url_poster: https://res.cloudinary.com/dkyd429md/image/upload/v1668802710/Plex%20-%20PMM%20images/carrs-toons_mdr7gc.jpg
  Ice Age Shorts:
    template:
      name: manual-shorts-collection
    tmdb_movie:
      - 17963
      - 46247
      - 21044
      - 55692
      - 98857
      - 367326
      - 421725
    tmdb_movie_details:
      - 17963 Ice Age
  Pixar Short Films Collection:
    template:
      name: manual-shorts-collection
    tmdb_movie:
      - 13924
      - 13925
      - 13926
      - 13927
      - 13928
      - 13929
      - 13930
      - 13931
      - 13062
      - 13932
      - 13933
      - 13934
      - 13060
      - 13061
      - 13042
      - 13413
      - 24480
      - 24589
      - 72962
      - 40619
      - 77887
      - 145316
      - 82424
      - 141528
      - 83564
      - 130925
      - 141423
      - 200481
      - 258152
      - 286189
      - 286192
      - 345637
      - 355338
      - 399106
      - 427004
      - 433471
      - 483396
      - 514754
    url_poster: https://res.cloudinary.com/dkyd429md/image/upload/v1668782317/Plex%20-%20PMM%20images/pixar-short-films-collection-5223ed2f81276_vjp091.jpg
  The Simpsons Collection:
    template:
      name: manual-shorts-collection
    tmdb_movie:
      - 116440
      - 673595
      - 1045177
      - 825597
      - 846214
      - 877183
      - 962659
      - 1015602
    url_poster: https://res.cloudinary.com/dkyd429md/image/upload/v1668798305/Plex%20-%20PMM%20images/The-Simpsons_h78hal.jpg
  Walt Disney Treasures- On the Front Lines:
    template:
      name: manual-shorts-collection
    tmdb_movie:
      - 54485
      - 64697
      - 64706
      - 64695
      - 64692
      - 56627
      - 64708
      - 64702
      - 62598
      - 64662
      - 53620
      - 64704
      - 64593
      - 64659
      - 64663
      - 64658
      - 64595
      - 64701
      - 64703
      - 64707
      - 64657
      - 64698
      - 39089
      - 64705
      - 64691
      - 33600
      - 44480
      - 64693
      - 64648
      - 22779
    tmdb_movie_details:
      - 327919
  Walt Disney Treasures- The Chronological Donald, Volume Two:
    plex_search:
      all:
        title: A Day in the Life of Donald Duck
    template:
      name: manual-shorts-collection
    tmdb_movie:
      - 53458
      - 67604
      - 55461
      - 55371
      - 55395
      - 55462
      - 57199
      - 54485
      - 64706
      - 64695
      - 33600
      - 56627
      - 64702
      - 62598
      - 53620
      - 67702
      - 67598
      - 55407
      - 54482
      - 53745
      - 56631
      - 55354
      - 55541
      - 67143
      - 53916
      - 53491
      - 67149
      - 55365
      - 67712
      - 55548
      - 54411
      - 57235
      - 151417
    tmdb_movie_details:
      - 315597
