templates:
  TV-collection:
    collection_mode: hide
    minimum_items: 1
    collection_order: release
collections:
  Animaniacs:
    template:
      name: TV-collection
    tmdb_show:
      - 82
      - 107124
  Batman (DC Universe Animated) Collection:
    template:
      name: TV-collection
    tmdb_show:
      - 2098
      - 513
  Batman 1966:
    template:
      name: TV-collection
    tmdb_show:
      - 2287
  Battlestar Galactica (Reboot):
    template:
      name: TV-collection
    tmdb_show:
      - 71365
      - 1972
  Clarissa:
    template:
      name: TV-collection
    tmdb_show:
      - 249
  Cowboy Bebop:
    template:
      name: TV-collection
    tmdb_show:
      - 30991
  Daria:
    template:
      name: TV-collection
    tmdb_show:
      - 2131
  Deadwood:
    template:
      name: TV-collection
    tmdb_show:
      - 1406
  Dragon Ball Collection:
    sort_title: Dragon_Ball_1
    template:
      name: TV-collection
    tmdb_show:
      - 12609
  Dragon Ball Complete Collection:
    sort_title: Dragon_Ball_4
    template:
      name: TV-collection
    tmdb_show:
      - 12609
      - 12971
      - 61709
      - 62715
      - 12697
    url_poster: https://res.cloudinary.com/dkyd429md/image/upload/v1668802950/Plex%20-%20PMM%20images/dragonball_xljkad.jpg
  Dragon Ball Super Collection:
    sort_title: Dragon_Ball_3
    template:
      name: TV-collection
    tmdb_show:
      - 62715
  Dragon Ball Z Collection:
    sort_title: Dragon_Ball_2
    template:
      name: TV-collection
    tmdb_show:
      - 12971
  DuckTales:
    template:
      name: TV-collection
    tmdb_show:
      - 720
  Evil Dead:
    tmdb_show:
      - 62264
  Friends:
    template:
      name: TV-collection
    tmdb_show:
      - 1668
  G.I. Joe Collection:
    template:
      name: TV-collection
    tmdb_show:
      - 29200
  Lion Guard:
    template:
      name: TV-collection
    tmdb_show:
      - 64752
  Miraculous World:
    template:
      name: TV-collection
    tmdb_show:
      - 65334
  MonsterVerse:
    collection_mode: hide
    collection_order: custom
    mdblist_list: https://mdblist.com/lists/andcbii/test-list
    sync_mode: sync
    url_poster: https://res.cloudinary.com/dkyd429md/image/upload/v1712692272/Plex%20-%20PMM%20images/MonsterVerse_Collection_fi8pme.png
  Parks and Recreation:
    template:
      name: TV-collection
    tmdb_show:
      - 8592
  Power Rangers:
    template:
      name: TV-collection
    tmdb_show:
      - 2328
  Psych:
    template:
      name: TV-collection
    tmdb_show:
      - 1447
  Star Trek:
    sort_title: Star_Trek_9999
    template:
      name: TV-collection
    tmdb_show:
      - 253
      - 1992
      - 655
      - 580
      - 1855
      - 314
      - 67198
      - 82491
      - 85949
      - 85948
      - 106393
      - 103516
  'Star Trek: The Next Generation':
    sort_title: Star_Trek_1987
    template:
      name: TV-collection
    tmdb_show:
      - 655
  'Star Trek: The Original Series':
    sort_title: Star_Trek_1966
    template:
      name: TV-collection
    tmdb_show:
      - 253
      - 1992
  TMNT-2012:
    template:
      name: TV-collection
    tmdb_show:
      - 51817
  The Simpsons:
    template:
      name: TV-collection
    tmdb_show:
      - 456
  Transformers 1984:
    template:
      name: TV-collection
    tmdb_show:
      - 4269
  Zoey's Extraordinary:
    template:
      name: TV-collection
    tmdb_show:
      - 95941
